-- Products:
create table public.products (
  id bigint generated by default as identity not null,
  image text null default 'default.png'::text,
  name text null,
  category_id bigint null,
  price double precision null,
  stock bigint null,
  description text null,
  constraint products_pkey primary key (id),
  constraint products_id_key unique (id),
  constraint products_category_id_fkey foreign KEY (category_id) references categories (id)
) TABLESPACE pg_default;

-- Categories:
create table public.categories (
  id bigint generated by default as identity not null,
  name text null,
  slug text null,
  status boolean null,
  image text null default 'default.png'::text,
  constraint categories_pkey primary key (id)
) TABLESPACE pg_default;

-- Orders:
create table public.orders (
  id bigint generated by default as identity not null,
  created_at timestamp with time zone null default now(),
  status text null,
  constraint orders_pkey primary key (id)
) TABLESPACE pg_default;

-- OrderItems:
create table public.order - items (
  id bigint generated by default as identity not null,
  order_id bigint null,
  product_id bigint null,
  quantity bigint null,
  unit_price double precision null,
  constraint order - items_pkey primary key (id),
  constraint order - items_order_id_fkey foreign KEY (order_id) references orders (id),
  constraint order - items_product_id_fkey foreign KEY (product_id) references products (id)
) TABLESPACE pg_default;